### ISSUE TITLE
not loading cura metadata from 3mf - xml namespace  issue

### ISSUE THREAD

**Issue by kcris** [Ultimaker/libSavitar#22]
**Application version**
4.4.0

**Platform**
windows 10, 64 bit

**Printer**
none

**Reproduction steps**
1. load 3mf file which contains metadata, attributes under the correct cura namespace `http://software.ultimaker.com/xml/cura/3mf/2015/10` but using a namespace _prefix_ other than `cura`
2. file is loaded but metadata is ignored because the namespace _prefix_ is not literally set to `cura`
(which is incorrect, `cura` is an xml namespace _prefix_, and a namespace _prefix_ acts like a handle for the namespace and is otherwise meaningless, so as long as the namespace is correct, the namespace _prefix_ should make no difference whatsoever when loading the 3mf xml, in Cura or any other software)

**Screenshot(s)**
I have used a 3mf file with this model contents
```
<model... xmlns:customXMLNS0="http://software.ultimaker.com/xml/cura/3mf/2015/10" ...>
  ... <metadata name="customXMLNS0:extruder_nr" type="string" preserve="1">0</metadata>
</model>
```

**Actual results**
Model will be loaded but cura metadata is ignored.

**Expected results**
The namespace I used (not the _prefix_) is correct = http://software.ultimaker.com/xml/cura/3mf/2015/10.
Metadata should be loaded independent of the namespace _prefix_ used (in my case `customXMLNS0`).

**Workaround results**
By changing the namespace _prefix_ to `cura`, Ultimaker will correctly load the metadata, which means that you are searching for a specific namespace _prefix_ and not the namespace itself.

This is incorrect according to standard xml functionality. Loading should work the same, no matter what namespace _prefix_ is used.

**Project file**

**Log file**

**Additional information**

see plugins
* plugins/3MFReader/ThreeMFReader.py
* plugins/3MFWriter/ThreeMFWriter.py

https://en.wikipedia.org/wiki/XML_namespace

**Comment by rburema** [comment]
Devs: We created internal ticket CURA-7120 for this (in progress now).

**Comment by Ghostkeeper** [comment]
This is fixed for the upcoming release. Thanks for the bug report!
