### ISSUE TITLE
Linux 64 bits issue

### ISSUE THREAD

**Issue by mariolpantunes** [Ultimaker/libSavitar#5]
Hi, in order to compile Cura (and all the libs) I had to patch up the CMakeLists.txt to correctly use Lib_Suffix.
I share my lib64.patch, if you found it acceptable can you add it to the code?
[lib64.txt](https://github.com/Ultimaker/libSavitar/files/1156553/lib64.txt)

**Comment by nallath** [comment]
Could you make a pull request for this?

**Comment by Ghostkeeper** [comment]
I've applied this patch with some slight modification, since the internet tells me that the `LIB_SUFFIX` variable isn't always defined. For me it was defined though. Anyway, it still works on Ubuntu. I hope that it now also works on your system.
