### ISSUE TITLE
Error in update

### ISSUE THREAD

**Issue by 5calV** [Ultimaker/libSavitar#52]
Updates fail:
Distro: EndeavourOS 
Kernel: 6.8.2-arch2-1

-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:4 (find_package):
  By not providing "Findstandardprojectsettings.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "standardprojectsettings", but CMake did not find one.

  Could not find a package configuration file provided by
  "standardprojectsettings" with any of the following names:

standardprojectsettingsConfig.cmake
standardprojectsettings-config.cmake

  Add the installation prefix of "standardprojectsettings" to
  CMAKE_PREFIX_PATH or set "standardprojectsettings_DIR" to a directory
  containing one of the above files.  If "standardprojectsettings" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
==> ERROR: An error occurred in build().
     Break off...
  -> Error building: libsavitar-exit status 4
  -> The following packages could not be installed. Manual intervention is required:
libsavitar - exit status 4

**Comment by motareis** [comment]
Same here, kernel 6.6.25-1-MANJARO (64-bit)

```
Erstelle libsavitar...
==> Erstelle Paket: libsavitar 5.3.0-0.1 (Mi 10 Apr 2024 07:59:20 CEST)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> libsavitar-5.3.0.tar.gz gefunden
==> Überprüfe source Dateien mit b2sums...
    libsavitar-5.3.0.tar.gz ... Erfolg
==> Entferne existierendes $srcdir/ Verzeichnis...
==> Entpacke Quellen...
  -> Entpacke libsavitar-5.3.0.tar.gz mit bsdtar
==> Beginne prepare()...
==> Entferne existierendes $pkgdir/ Verzeichnis...
==> Beginne build()...
CMake Warning (dev) at CMakeLists.txt:2 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:4 (find_package):
  By not providing "Findstandardprojectsettings.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "standardprojectsettings", but CMake did not find one.

  Could not find a package configuration file provided by
  "standardprojectsettings" with any of the following names:

    standardprojectsettingsConfig.cmake
    standardprojectsettings-config.cmake

  Add the installation prefix of "standardprojectsettings" to
  CMAKE_PREFIX_PATH or set "standardprojectsettings_DIR" to a directory
  containing one of the above files.  If "standardprojectsettings" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
```

**Comment by ramis-svitla** [comment]
Same here.
OS: Manjaro Linux x86_64
Kernel: 6.6.25-1-MANJARO

`Building libsavitar...
==> Making package: libsavitar 5.3.0-0.1 (we, 10-Apt-2024 20:56:32 +0200)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading libsavitar-5.3.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 25406    0 25406    0     0  15391      0 --:--:--  0:00:01 --:--:-- 18722
==> Validating source files with b2sums...
    libsavitar-5.3.0.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting libsavitar-5.3.0.tar.gz with bsdtar
==> Starting prepare()...
==> Starting build()...
CMake Warning (dev) at CMakeLists.txt:2 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:4 (find_package):
  By not providing "Findstandardprojectsettings.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "standardprojectsettings", but CMake did not find one.

  Could not find a package configuration file provided by
  "standardprojectsettings" with any of the following names:

    standardprojectsettingsConfig.cmake
    standardprojectsettings-config.cmake

  Add the installation prefix of "standardprojectsettings" to
  CMAKE_PREFIX_PATH or set "standardprojectsettings_DIR" to a directory
  containing one of the above files.  If "standardprojectsettings" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
==> ERROR: A failure occurred in build().
    Aborting...`

**Comment by jellespijker** [comment]
At a first glance this is happening with the package managers of Linux distributions. Please report these issue at their repository. 

Building from source with Conan as per instruction will pull in the standardprojects.cmake (https://github.com/Ultimaker/conan-ultimaker-index/tree/main/recipes%2Fstandardprojectsettings%2Fall) automatically. 
This is also the only build process that we officially supprt

**Comment by jellespijker** [comment]
See https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source for our instructions on building Cura from source
