### ISSUE TITLE
License of src/Face.h

### ISSUE THREAD

**Issue by onitake** [Ultimaker/libSavitar#6]
`src/Face.h` says this file is released under GPL-3+, while LICENSE and the rest of libSavitar says LGPL-3+.

Was this an oversight, or is this file really GPL-3+?

**Comment by nallath** [comment]
I think this is an oversight.

**Comment by Ghostkeeper** [comment]
Indeed it is, caused by some files not even mentioning that they were AGPL previously. I've fixed that right up. Thanks for noticing.
